INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (1, 'Madrid');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (2, 'Barcelona');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (3, 'Valencia');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (4, 'Sevilla');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (5, 'Zaragoza');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (6, 'Málaga');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (7, 'Murcia');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (8, 'Palma de Mallorca');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (9, 'Las Palmas');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (10, 'Alicante');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (11, 'Cádiz');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (12, 'Castellón');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (13, 'Burgos');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (14, 'Salamanca');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (15, 'La Rioja');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (16, 'Pontevedra');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (17, 'Córdoba');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (18, 'Toledo');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (19, 'Vigo');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (20, 'Huelva');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (21, 'Jaén');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (22, 'Álava');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (23, 'Guipúzcoa');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (24, 'Vizcaya');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (25, 'Gerona');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (26, 'Lérida');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (27, 'Segovia');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (28, 'Ávila');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (29, 'Soria');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (30, 'Cuenca');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (31, 'Badajoz');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (32, 'Cáceres');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (33, 'Teruel');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (34, 'Huesca');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (35, 'Guadalajara');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (36, 'Albacete');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (37, 'La Coruña');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (38, 'Tarragona');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (39, 'León');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (40, 'Baleares');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (41, 'Cantabria');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (42, 'Castilla y León');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (43, 'Extremadura');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (44, 'Navarra');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (45, 'La Rioja');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (46, 'Ceuta');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (47, 'Melilla');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (48, 'Madrid');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (49, 'Zaragoza');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (50, 'Alicante');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (51, 'Madrid');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (52, 'Barcelona');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (53, 'Valencia');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (54, 'Sevilla');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (55, 'Zaragoza');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (56, 'Málaga');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (57, 'Murcia');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (58, 'Palma de Mallorca');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (59, 'Las Palmas');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (60, 'Alicante');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (61, 'Cádiz');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (62, 'Castellón');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (63, 'Burgos');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (64, 'Salamanca');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (65, 'La Rioja');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (66, 'Pontevedra');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (67, 'Córdoba');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (68, 'Toledo');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (69, 'Vigo');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (70, 'Huelva');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (71, 'Jaén');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (72, 'Álava');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (73, 'Guipúzcoa');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (74, 'Vizcaya');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (75, 'Gerona');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (76, 'Lérida');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (77, 'Segovia');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (78, 'Ávila');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (79, 'Soria');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (80, 'Cuenca');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (81, 'Badajoz');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (82, 'Cáceres');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (83, 'Teruel');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (84, 'Huesca');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (85, 'Guadalajara');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (86, 'Albacete');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (87, 'La Coruña');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (88, 'Tarragona');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (89, 'León');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (90, 'Baleares');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (91, 'Cantabria');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (92, 'Castilla y León');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (93, 'Extremadura');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (94, 'Navarra');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (95, 'La Rioja');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (96, 'Ceuta');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (97, 'Melilla');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (98, 'Madrid');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (99, 'Zaragoza');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (100, 'Alicante');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (101, 'Madrid');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (102, 'Barcelona');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (103, 'Valencia');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (104, 'Sevilla');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (105, 'Zaragoza');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (106, 'Málaga');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (107, 'Murcia');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (108, 'Palma de Mallorca');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (109, 'Las Palmas');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (110, 'Alicante');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (111, 'Cádiz');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (112, 'Castellón');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (113, 'Burgos');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (114, 'Salamanca');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (115, 'La Rioja');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (116, 'Pontevedra');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (117, 'Córdoba');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (118, 'Toledo');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (119, 'Vigo');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (120, 'Huelva');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (121, 'Jaén');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (122, 'Álava');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (123, 'Guipúzcoa');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (124, 'Vizcaya');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (125, 'Gerona');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (126, 'Lérida');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (127, 'Segovia');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (128, 'Ávila');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (129, 'Soria');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (130, 'Cuenca');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (131, 'Badajoz');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (132, 'Cáceres');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (133, 'Teruel');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (134, 'Huesca');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (135, 'Guadalajara');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (136, 'Albacete');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (137, 'La Coruña');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (138, 'Tarragona');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (139, 'León');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (140, 'Baleares');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (141, 'Cantabria');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (142, 'Castilla y León');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (143, 'Extremadura');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (144, 'Navarra');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (145, 'La Rioja');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (146, 'Ceuta');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (147, 'Melilla');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (148, 'Madrid');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (149, 'Zaragoza');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (150, 'Alicante');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (151, 'Murcia');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (152, 'Valencia');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (153, 'Palencia');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (154, 'Burgos');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (155, 'Segovia');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (156, 'Salamanca');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (157, 'Valladolid');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (158, 'Ávila');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (159, 'Zamora');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (160, 'Huesca');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (161, 'Teruel');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (162, 'La Coruña');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (163, 'Lugo');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (164, 'Ourense');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (165, 'Cáceres');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (166, 'Badajoz');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (167, 'Guadalajara');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (168, 'Albacete');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (169, 'Toledo');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (170, 'Ciudad Real');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (171, 'Cuenca');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (172, 'Jaén');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (173, 'Córdoba');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (174, 'Granada');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (175, 'Almería');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (176, 'Málaga');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (177, 'Soria');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (178, 'Huelva');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (179, 'Baleares');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (180, 'Girona');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (181, 'Lleida');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (182, 'Tarragona');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (183, 'Santa Cruz de Tenerife');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (184, 'Las Palmas');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (185, 'Cantabria');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (186, 'Castilla y León');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (187, 'Navarra');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (188, 'Madrid');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (189, 'Castilla-La Mancha');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (190, 'Andalucía');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (191, 'Cataluña');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (192, 'Galicia');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (193, 'País Vasco');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (194, 'Comunidad Valenciana');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (195, 'Extremadura');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (196, 'Aragón');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (197, 'Murcia');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (198, 'Castilla-La Mancha');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (199, 'Canarias');
INSERT INTO FIDE_PROVINCIA_TB (id_provincia, nombre) VALUES (200, 'Islas Baleares');
