INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (1, 1, 'Madrid Centro');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (2, 1, 'Alcalá de Henares');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (3, 2, 'Badajoz Centro');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (4, 2, 'Mérida');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (5, 3, 'A Coruña Centro');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (6, 3, 'Santiago de Compostela');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (7, 4, 'Lugo Centro');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (8, 4, 'Monforte de Lemos');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (9, 5, 'Segovia Centro');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (10, 5, 'Sepúlveda');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (11, 6, 'Salamanca Centro');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (12, 6, 'Ciudad Rodrigo');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (13, 7, 'Valladolid Centro');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (14, 7, 'Medina del Campo');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (15, 8, 'Ávila Centro');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (16, 8, 'Arévalo');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (17, 9, 'Zamora Centro');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (18, 9, 'Benavente');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (19, 10, 'Huesca Centro');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (20, 10, 'Jaca');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (21, 11, 'Teruel Centro');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (22, 11, 'Alcañiz');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (23, 12, 'La Coruña Norte');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (24, 12, 'Ferrol');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (25, 13, 'Lugo Norte');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (26, 13, 'Ribeira');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (27, 14, 'Ourense Centro');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (28, 14, 'Verín');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (29, 15, 'Cáceres Centro');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (30, 15, 'Plasencia');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (31, 16, 'Badajoz Norte');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (32, 16, 'Don Benito');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (33, 17, 'Guadalajara Centro');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (34, 17, 'Azuqueca de Henares');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (35, 18, 'Albacete Centro');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (36, 18, 'Hellín');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (37, 19, 'Toledo Centro');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (38, 19, 'Talavera de la Reina');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (39, 20, 'Ciudad Real Centro');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (40, 20, 'Manzanares');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (41, 21, 'Cuenca Centro');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (42, 21, 'San Clemente');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (43, 22, 'Jaén Centro');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (44, 22, 'Úbeda');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (45, 23, 'Córdoba Centro');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (46, 23, 'Puente Genil');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (47, 24, 'Granada Centro');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (48, 24, 'Almuñécar');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (49, 25, 'Almería Centro');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (50, 25, 'El Ejido');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (51, 26, 'Cartagena');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (52, 26, 'Murcia Centro');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (53, 27, 'Santa Cruz de Tenerife');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (54, 27, 'La Laguna');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (55, 28, 'Las Palmas de Gran Canaria');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (56, 28, 'Telde');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (57, 29, 'Cádiz');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (58, 29, 'San Fernando');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (59, 30, 'Huelva');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (60, 30, 'Lepe');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (61, 31, 'Sevilla');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (62, 31, 'Dos Hermanas');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (63, 32, 'Córdoba');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (64, 32, 'Puente Genil');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (65, 33, 'Alcalá la Real');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (66, 33, 'Jaén');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (67, 34, 'Alicante');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (68, 34, 'Elche');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (69, 35, 'Castellón');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (70, 35, 'Vinaroz');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (71, 36, 'Valencia');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (72, 36, 'Gandía');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (73, 37, 'Barcelona');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (74, 37, 'Terrassa');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (75, 38, 'Tarragona');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (76, 38, 'Reus');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (77, 39, 'Girona');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (78, 39, 'Figueres');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (79, 40, 'Lleida');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (80, 40, 'Balaguer');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (81, 41, 'Palencia');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (82, 41, 'Villamuriel de Cerrato');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (83, 42, 'Ávila');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (84, 42, 'El Tiemblo');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (85, 43, 'Segovia');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (86, 43, 'La Granja de San Ildefonso');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (87, 44, 'Soria');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (88, 44, 'Ólvega');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (89, 45, 'Logroño');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (90, 45, 'Calahorra');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (91, 46, 'Burgos');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (92, 46, 'Aranda de Duero');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (93, 47, 'Vitoria-Gasteiz');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (94, 47, 'Llodio');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (95, 48, 'Bilbao');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (96, 48, 'Getxo');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (97, 49, 'Pamplona');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (98, 49, 'Tudela');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (99, 50, 'Zaragoza');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (100, 50, 'Cuarte de Huerva');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (101, 1, 'Móstoles');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (102, 2, 'Zafra');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (103, 3, 'Ferrol');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (104, 4, 'Viveiro');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (105, 5, 'Cuéllar');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (106, 6, 'Béjar');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (107, 7, 'Tordesillas');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (108, 8, 'Las Navas del Marqués');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (109, 9, 'Toro');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (110, 10, 'Barbastro');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (111, 11, 'Andorra (Teruel)');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (112, 12, 'Carballo');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (113, 13, 'Foz');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (114, 14, 'O Barco de Valdeorras');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (115, 15, 'Trujillo');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (116, 16, 'Zafra');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (117, 17, 'Sigüenza');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (118, 18, 'Villarrobledo');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (119, 19, 'Illescas');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (120, 20, 'Puertollano');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (121, 21, 'Tarancón');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (122, 22, 'Martos');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (123, 23, 'Lucena');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (124, 24, 'Motril');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (125, 25, 'Roquetas de Mar');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (126, 26, 'Lorca');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (127, 27, 'Puerto de la Cruz');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (128, 28, 'Arucas');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (129, 29, 'Chiclana de la Frontera');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (130, 30, 'Isla Cristina');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (131, 31, 'Utrera');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (132, 32, 'Baena');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (133, 33, 'Baeza');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (134, 34, 'Torrevieja');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (135, 35, 'Benicàssim');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (136, 36, 'Sagunto');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (137, 37, 'Sabadell');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (138, 38, 'Salou');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (139, 39, 'Olot');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (140, 40, 'Tàrrega');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (141, 41, 'Aguilar de Campoo');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (142, 42, 'Candeleda');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (143, 43, 'Nava de la Asunción');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (144, 44, 'Covaleda');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (145, 45, 'Haro');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (146, 46, 'Miranda de Ebro');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (147, 47, 'Amurrio');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (148, 48, 'Barakaldo');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (149, 49, 'Estella');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (150, 50, 'Ejea de los Caballeros');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (151, 50, 'Tauste');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (152, 50, 'Sádaba');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (153, 50, 'Gallur');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (154, 50, 'Luceni');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (155, 50, 'Mallén');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (156, 50, 'Alagón');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (157, 50, 'Remolinos');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (158, 50, 'Pedrola');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (159, 50, 'Magallón');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (160, 50, 'Borja');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (161, 50, 'Ainzón');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (162, 50, 'Fuendejalón');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (163, 50, 'Tarazona');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (164, 50, 'Novallas');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (165, 50, 'Ateca');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (166, 50, 'Calatayud');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (167, 50, 'Paracuellos de Jiloca');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (168, 50, 'Illueca');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (169, 50, 'Brea de Aragón');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (170, 50, 'Morata de Jalón');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (171, 50, 'La Almunia de Doña Godina');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (172, 50, 'Épila');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (173, 50, 'Ricla');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (174, 50, 'Cariñena');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (175, 50, 'Aguarón');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (176, 50, 'Daroca');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (177, 50, 'Molina de Aragón');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (178, 50, 'Used');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (179, 50, 'Calamocha');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (180, 50, 'Monreal del Campo');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (181, 50, 'Zaragoza');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (182, 50, 'Cuarte de Huerva');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (183, 50, 'Utebo');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (184, 50, 'Villanueva de Gállego');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (185, 50, 'Zuera');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (186, 50, 'San Mateo de Gállego');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (187, 50, 'Alfajarín');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (188, 50, 'El Burgo de Ebro');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (189, 50, 'La Puebla de Alfindén');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (190, 50, 'Pina de Ebro');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (191, 50, 'Fuentes de Ebro');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (192, 50, 'Quinto');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (193, 50, 'Belchite');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (194, 50, 'Lécera');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (195, 50, 'Azuara');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (196, 50, 'Maella');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (197, 50, 'Fabara');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (198, 50, 'Caspe');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (199, 50, 'Chiprana');
INSERT INTO FIDE_CANTON_TB (id_canton, id_provincia, nombre) VALUES (200, 50, 'Nonaspe');
