INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (1, 1, 'Carmen');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (2, 1, 'Merced');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (3, 1, 'Hospital');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (4, 1, 'Catedral');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (5, 1, 'Zapote');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (6, 1, 'San Francisco de Dos Ríos');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (7, 1, 'Uruca');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (8, 1, 'Mata Redonda');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (9, 1, 'Pavas');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (10, 1, 'Hatillo');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (11, 1, 'San Sebastián');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (12, 2, 'San Vicente');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (13, 2, 'San Jerónimo');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (14, 2, 'Trinidad');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (15, 3, 'Guadalupe');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (16, 3, 'San Francisco');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (17, 3, 'Calle Blancos');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (18, 3, 'Mata de Plátano');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (19, 3, 'Ipís');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (20, 3, 'Rancho Redondo');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (21, 3, 'Purral');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (22, 4, 'San Juan');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (23, 4, 'Cinco Esquinas');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (24, 4, 'Anselmo Llorente');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (25, 4, 'León XIII');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (26, 4, 'Colima');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (27, 5, 'San Isidro');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (28, 5, 'San Rafael');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (29, 5, 'Dulce Nombre de Jesús');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (30, 5, 'Patalillo');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (31, 5, 'Cascajal');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (32, 6, 'Aserrí');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (33, 6, 'Tarbaca');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (34, 6, 'Vuelta de Jorco');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (35, 6, 'San Gabriel');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (36, 6, 'Legua');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (37, 6, 'Monterrey');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (38, 7, 'Desamparados');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (39, 7, 'San Miguel');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (40, 7, 'San Juan de Dios');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (41, 7, 'San Rafael Arriba');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (42, 7, 'San Rafael Abajo');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (43, 7, 'Gravilias');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (44, 7, 'Los Guido');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (45, 8, 'Santo Domingo');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (46, 8, 'San Vicente');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (47, 8, 'San Miguel');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (48, 8, 'Paracito');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (49, 8, 'Santo Tomás');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (50, 8, 'Tures');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (51, 9, 'San Pedro');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (52, 9, 'Sabanilla');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (53, 9, 'Mercedes');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (54, 9, 'San Rafael');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (55, 9, 'San Pablo');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (56, 10, 'Curridabat');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (57, 10, 'Granadilla');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (58, 10, 'Sánchez');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (59, 10, 'Tirrases');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (60, 11, 'San Isidro');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (61, 11, 'San Ramón');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (62, 11, 'Damas');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (63, 11, 'Purral');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (64, 12, 'Santa Ana');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (65, 12, 'Salitral');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (66, 12, 'Pozos');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (67, 12, 'Uruca');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (68, 12, 'Piedades');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (69, 12, 'Brasil');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (70, 13, 'Escazú');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (71, 13, 'San Rafael');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (72, 13, 'San Antonio');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (73, 14, 'Alajuelita');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (74, 14, 'San Josecito');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (75, 14, 'San Antonio');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (76, 14, 'Concepción');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (77, 14, 'San Felipe');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (78, 15, 'Vázquez de Coronado');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (79, 15, 'San Isidro');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (80, 15, 'Dulce Nombre de Jesús');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (81, 15, 'Patalillo');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (82, 15, 'Cascajal');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (83, 16, 'Mora');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (84, 16, 'Guayabo');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (85, 16, 'Tabarcia');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (86, 16, 'Piedras Negras');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (87, 16, 'Picagres');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (88, 17, 'Goicoechea');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (89, 17, 'San Francisco');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (90, 17, 'Calle Blancos');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (91, 17, 'Mata de Plátano');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (92, 17, 'Ipís');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (93, 17, 'Rancho Redondo');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (94, 17, 'Purral');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (95, 18, 'Montes de Oca');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (96, 18, 'Sabanilla');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (97, 18, 'Mercedes');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (98, 18, 'San Rafael');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (99, 18, 'San Pablo');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (100, 18, 'San Pedro');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (101, 19, 'Liberia');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (102, 19, 'Cañas Dulces');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (103, 19, 'Mayorga');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (104, 19, 'Nacascolo');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (105, 19, 'Curubandé');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (106, 20, 'Nicoya');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (107, 20, 'Mansión');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (108, 20, 'San Antonio');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (109, 20, 'Quebrada Honda');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (110, 20, 'Sámara');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (111, 20, 'Nosara');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (112, 20, 'Belén de Nosarita');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (113, 21, 'Santa Cruz');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (114, 21, 'Bolsón');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (115, 21, 'Veintisiete de Abril');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (116, 21, 'Tempate');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (117, 21, 'Cartagena');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (118, 21, 'Cuajiniquil');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (119, 21, 'Diriá');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (120, 21, 'Cabo Velas');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (121, 21, 'Tamarindo');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (122, 22, 'Filadelfia');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (123, 22, 'Palmira');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (124, 22, 'Sardinal');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (125, 22, 'Belén');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (126, 23, 'Cañas');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (127, 23, 'Palmira');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (128, 23, 'San Miguel');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (129, 23, 'Bebedero');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (130, 23, 'Porozal');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (131, 24, 'Bagaces');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (132, 24, 'Fortuna');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (133, 24, 'Mogote');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (134, 24, 'Río Naranjo');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (135, 25, 'Tilarán');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (136, 25, 'Quebrada Grande');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (137, 25, 'Tronadora');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (138, 25, 'Santa Rosa');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (139, 25, 'Líbano');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (140, 25, 'Tierras Morenas');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (141, 25, 'Arenal');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (142, 26, 'Puerto Carrillo');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (143, 26, 'Puerto San Pablo');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (144, 26, 'Puerto Jesús');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (145, 26, 'San Blas');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (146, 26, 'Nandayure');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (147, 26, 'Zapotal');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (148, 26, 'San Pablo');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (149, 26, 'Bejuco');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (150, 26, 'Santa Rita');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (151, 27, 'Puntarenas');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (152, 27, 'Chacarita');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (153, 27, 'La Ceiba');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (154, 27, 'Barranca');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (155, 27, 'Arío');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (156, 27, 'Isla del Coco');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (157, 28, 'Esparza');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (158, 28, 'Bajo de Los Rodríguez');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (159, 28, 'Macacona');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (160, 28, 'Quepos');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (161, 28, 'Naranjito');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (162, 28, 'Savegre');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (163, 28, 'Villanueva');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (164, 29, 'Aserrí');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (165, 29, 'Candelaria');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (166, 29, 'San Gabriel');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (167, 29, 'Tarbaca');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (168, 30, 'San José');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (169, 30, 'Pavas');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (170, 30, 'La Uruca');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (171, 30, 'La Trinidad');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (172, 31, 'Curridabat');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (173, 31, 'Granadilla');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (174, 31, 'Sánchez');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (175, 31, 'Tirrases');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (176, 32, 'San Antonio');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (177, 32, 'Bajo de Los Rodríguez');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (178, 32, 'Macacona');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (179, 32, 'Quepos');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (180, 32, 'Naranjito');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (181, 32, 'Savegre');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (182, 32, 'Villanueva');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (183, 33, 'San José');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (184, 33, 'Pavas');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (185, 33, 'La Uruca');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (186, 33, 'La Trinidad');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (187, 34, 'Santa Teresa');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (188, 34, 'Bajo de Los Rodríguez');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (189, 34, 'Macacona');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (190, 34, 'Quepos');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (191, 34, 'Naranjito');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (192, 35, 'San Rafael');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (193, 35, 'La Perla');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (194, 35, 'San Pedro');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (195, 35, 'La Trinidad');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (196, 35, 'La Uruca');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (197, 36, 'Santa Teresita');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (198, 36, 'Naranjito');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (199, 36, 'Bajo de Los Rodríguez');
INSERT INTO FIDE_DISTRITO_TB (id_distrito, id_canton, nombre) VALUES (200, 36, 'Macacona');

