INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (1, 'Ensaladas', 'Variedad de ensaladas frescas y saludables.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (2, 'Sopas', 'Deliciosas sopas y cremas caseras.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (3, 'Antipastos', 'Selección de aperitivos y entrantes.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (4, 'Tapas', 'Pequeñas porciones de platos tradicionales.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (5, 'Ceviches', 'Preparaciones frescas de pescado y mariscos.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (6, 'Pasta', 'Variedad de pastas italianas, tradicionales y gourmet.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (7, 'Pizzas', 'Deliciosas pizzas con diferentes tipos de masa y toppings.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (8, 'Carnes', 'Selección de carnes de alta calidad para todos los gustos.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (9, 'Mariscos', 'Frescos mariscos de la costa preparados con especias únicas.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (10, 'Postres', 'Dulces y postres caseros para endulzar tu día.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (11, 'Sandwiches', 'Sándwiches artesanales con ingredientes frescos.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (12, 'Bebidas', 'Variedad de bebidas frías y calientes para acompañar cualquier platillo.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (13, 'Burgers', 'Jugosas hamburguesas con diferentes tipos de carne y toppings.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (14, 'Tacos', 'Auténticos tacos con salsas tradicionales y tortillas frescas.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (15, 'Sushi', 'Deliciosos rolls de sushi frescos con pescado de calidad.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (16, 'Poke', 'Platos frescos de pescado y vegetales estilo hawaiano.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (17, 'Paellas', 'Tradicional paella española con mariscos, carnes y verduras.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (18, 'Curry', 'Platos con curry especiado y sabroso de diferentes culturas.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (19, 'Burritos', 'Sabor mexicano en cada bocado con ingredientes frescos.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (20, 'Enchiladas', 'Deliciosas enchiladas con salsas caseras y carne a elección.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (21, 'Kebabs', 'Exquisitos kebabs de carne o vegetales asados a la perfección.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (22, 'Tortas', 'Sándwiches mexicanos rellenos de diferentes carnes y aderezos.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (23, 'Wraps', 'Tortillas rellenas de ingredientes frescos y deliciosos.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (24, 'Falafel', 'Bocaditos de garbanzo fritos con especias y salsa tahini.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (25, 'Fideos', 'Variedad de fideos asiáticos, europeos y tradicionales.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (26, 'Quiches', 'Deliciosas quiches caseras con diferentes rellenos.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (27, 'Crostinis', 'Tostas crujientes con variedad de toppings frescos.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (28, 'Crepes', 'Suaves y deliciosas crepes dulces o saladas.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (29, 'Bacon', 'Platos con tocino, uno de los ingredientes más sabrosos.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (30, 'Chiles en Nogada', 'Tradicional plato mexicano con carne y salsa de nuez.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (31, 'Tamales', 'Deliciosos tamales con diferentes rellenos y salsas.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (32, 'Ceviche', 'Fresco ceviche con mariscos y jugo de limón.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (33, 'Bebidas Exóticas', 'Bebidas refrescantes hechas con frutas exóticas.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (34, 'Lasaña', 'Capas de pasta, carne y salsa bechamel.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (35, 'Ramen', 'Tradicional sopa japonesa con fideos y toppings.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (36, 'Tartas', 'Postres suaves y cremosos en base a frutas y crema.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (37, 'Salsas', 'Variedad de salsas caseras para acompañar cualquier platillo.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (38, 'Fajitas', 'Deliciosas fajitas con carne y vegetales salteados.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (39, 'Salmón', 'Exquisitas preparaciones con salmón fresco y marinado.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (40, 'Costillas', 'Costillas de cerdo o res, marinadas y asadas a la perfección.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (41, 'Tortillas', 'Tortillas frescas para acompañar diferentes platillos.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (42, 'Ceviche de Atún', 'Fresco ceviche de atún con aguacate y cebolla morada.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (43, 'Pescado al Horno', 'Pescado fresco horneado con hierbas y especias.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (44, 'Papas Fritas', 'Papas fritas crocantes, el acompañante perfecto.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (45, 'Croquetas', 'Deliciosas croquetas rellenas de pollo, carne o queso.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (46, 'Arroz', 'Arroz en sus distintas preparaciones, desde pilaf hasta al curry.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (47, 'Tortas de Pescado', 'Tortas crujientes rellenas de pescado y aderezos especiales.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (48, 'Pechuga de Pollo', 'Pechugas de pollo preparadas de distintas maneras.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (49, 'Fideos Asiáticos', 'Fideos asiáticos en caldo o salteados con vegetales.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (50, 'Galletas', 'Galletas caseras de diferentes sabores como chocolate y vainilla.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (51, 'Cordero', 'Cordero preparado con especias tradicionales y asado lentamente.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (52, 'Panecillos', 'Panecillos frescos ideales para acompañar cualquier platillo.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (53, 'Bacalhau', 'Tradicional bacalao portugués, un manjar del mar.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (54, 'Gambas', 'Gambas frescas preparadas con ajo y limón.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (55, 'Brochetas', 'Brochetas de carne, pollo o vegetales a la parrilla.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (56, 'Noodles', 'Fideos asiáticos servidos en caldo o salteados.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (57, 'Pavo', 'Pavo asado o en diferentes presentaciones, ideal para ocasiones especiales.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (58, 'Aguachile', 'Fresco aguachile con camarones y chile fresco.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (59, 'Empanadas', 'Empanadas rellenas de carne, pollo o vegetales.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (60, 'Arepas', 'Deliciosas arepas rellenas con variedad de ingredientes.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (61, 'Mole', 'Mole casero con sabores intensos y especias exóticas.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (62, 'Galletas Saladas', 'Galletas crujientes y saladas perfectas para acompañar quesos.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (63, 'Cochinita Pibil', 'Carnes de cerdo cocinadas lentamente con achiote y especias.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (64, 'Sopes', 'Sopes mexicanos, pequeñas tortas cubiertas con guisos y salsas.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (65, 'Ropa Vieja', 'Plato cubano tradicional con carne desmenuzada y verduras.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (66, 'Tartar', 'Tartar de carne o pescado fresco con salsa especial.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (67, 'Maki', 'Rollos de sushi con pescados frescos y verduras.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (68, 'Katsu', 'Filete empanado y frito, servido con salsa tonkatsu.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (69, 'Arroz con Pollo', 'Plato clásico de arroz con pollo y verduras.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (70, 'Frittata', 'Frittata italiana, una mezcla de huevos con vegetales y queso.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (71, 'Tostadas', 'Tostadas con distintos ingredientes como guacamole o carne.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (72, 'Dumplings', 'Dumplings rellenos de carne o vegetales, al vapor o fritos.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (73, 'Churros', 'Dulces churros acompañados de chocolate caliente.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (74, 'Tempura', 'Verduras y mariscos empanados y fritos al estilo japonés.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (75, 'Langosta', 'Deliciosa langosta preparada con mantequilla y ajo.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (76, 'Patatas Bravas', 'Patatas fritas con una salsa picante y sabrosa.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (77, 'Tortillas de Maíz', 'Tortillas de maíz frescas para acompañar diferentes platillos.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (78, 'Pollo al Curry', 'Pollo preparado con una mezcla especiada de curry y crema.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (79, 'Blinis', 'Pequeñas crepes rusas, servidas con crema agria y caviar.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (80, 'Steak', 'Jugoso corte de carne asada o a la parrilla.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (81, 'Fideos de Arroz', 'Fideos de arroz al estilo asiático, servidos con vegetales y salsa.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (82, 'Pannacotta', 'Postre italiano de crema suave con frutas frescas.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (83, 'Chicharrón', 'Crujiente chicharrón de cerdo, ideal para acompañar guisos.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (84, 'Tortilla Española', 'Tortilla española de patatas, huevos y cebolla.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (85, 'Pasta Fresca', 'Pasta hecha a mano con ingredientes frescos.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (86, 'Pizza Margherita', 'Pizza clásica con tomate, mozzarella y albahaca.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (87, 'Fajitas de Pollo', 'Fajitas con pollo, pimientos y cebollas salteados.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (88, 'Pan con Ajo', 'Pan tostado con mantequilla y ajo, ideal como acompañamiento.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (89, 'Sardinas', 'Sardinas frescas asadas o a la parrilla.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (90, 'Pasta al Pesto', 'Pasta fresca con salsa de albahaca y piñones.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (91, 'Crispy Tofu', 'Tofu crujiente, perfecto para acompañar ensaladas o sopas.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (92, 'Pavo Relleno', 'Pavo relleno con hierbas y frutos secos, ideal para celebraciones.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (93, 'Sopa de Lentejas', 'Sopa nutritiva de lentejas con verduras frescas.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (94, 'Bocadillos', 'Sándwiches pequeños rellenos de diferentes ingredientes.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (95, 'Risotto', 'Arroz cremoso al estilo italiano, con setas o mariscos.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (96, 'Camarones al Ajillo', 'Camarones salteados con ajo, perejil y limón.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (97, 'Pollo Asado', 'Pollo asado con hierbas y especias al gusto.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (98, 'Pasteles', 'Pasteles de frutas, crema o chocolate.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (99, 'Ensalada Caprese', 'Ensalada fresca de tomate, mozzarella y albahaca.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (100, 'Sopa de Calabaza', 'Sopa cremosa de calabaza, ideal para los días fríos.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (101, 'Tacos al Pastor', 'Tacos con carne de cerdo marinada, piña y salsa especial.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (102, 'Penne Arrabbiata', 'Pasta penne con salsa picante de tomate y ajo.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (103, 'Ratatouille', 'Guiso de vegetales provenzal, saludable y sabroso.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (104, 'Babka', 'Pan dulce tradicional con chocolate o canela.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (105, 'Cheeseburger', 'Hamburguesa con queso derretido y otros deliciosos toppings.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (106, 'Sopa de Tomate', 'Sopa cremosa de tomate, perfecta para acompañar pan.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (107, 'Chili con Carne', 'Guiso de carne molida con frijoles y especias.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (108, 'Peking Duck', 'Pato de Pekín con piel crujiente, servido con pancakes.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (109, 'Ceviche Mixto', 'Mezcla de mariscos frescos en jugo de limón y cilantro.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (110, 'Pupusas', 'Tradicionales pupusas salvadoreñas rellenas de queso y frijoles.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (111, 'Sopa de Mariscos', 'Sopa caliente con una mezcla de mariscos frescos.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (112, 'Panettone', 'Pastel italiano de frutas y nueces, ideal para navidad.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (113, 'Moussaka', 'Plato griego de berenjenas con carne y bechamel.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (114, 'Waffles', 'Crujientes waffles con frutas y sirope.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (115, 'Kumara', 'Puré de batata dulce, un acompañante suave y dulce.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (116, 'Sausage Rolls', 'Rollos rellenos de salchicha en masa hojaldrada.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (117, 'Cornbread', 'Pan de maíz esponjoso, ideal para acompañar guisos.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (118, 'Fettuccine Alfredo', 'Pasta fettuccine con salsa cremosa de queso parmesano.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (119, 'Paella Valenciana', 'Paella tradicional con mariscos, pollo y conejo.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (120, 'Boeuf Bourguignon', 'Estofado de carne de res cocinado con vino tinto.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (121, 'Pho', 'Sopa vietnamita con fideos, carne y hierbas.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (122, 'Tostones', 'Plátanos fritos y crujientes, un acompañante perfecto.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (123, 'Ensalada de Atún', 'Ensalada fresca con atún, lechuga, tomate y cebolla.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (124, 'Lasagna Vegetariana', 'Lasagna sin carne, rellena de verduras y queso.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (125, 'Escargots', 'Caracoles al ajillo, una delicia de la gastronomía francesa.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (126, 'Bagels', 'Panecillos redondos con agujero, ideales para desayunos.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (127, 'Baked Ziti', 'Pasta ziti horneada con salsa de tomate y queso.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (128, 'Chimichanga', 'Taco frito relleno de carne, pollo o queso.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (129, 'Pizza Hawaiana', 'Pizza con jamón, piña y queso.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (130, 'Sopa Minestrone', 'Sopa italiana llena de vegetales y pasta.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (131, 'Baklava', 'Dulce tradicional turco con nueces y miel.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (132, 'Goulash', 'Estofado húngaro de carne con paprika y verduras.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (133, 'Sopa de Acelga', 'Sopa ligera con acelgas y vegetales frescos.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (134, 'Tiramisu', 'Postre italiano de capas de café y mascarpone.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (135, 'Peking Duck Pancakes', 'Pato de Pekín servido con pancakes y salsa hoisin.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (136, 'Shakshuka', 'Plato israelí de huevos cocidos en salsa de tomate picante.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (137, 'Chicken Tikka Masala', 'Pollo en salsa de tomate especiada al estilo indio.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (138, 'Clams', 'Almejas frescas servidas con mantequilla o en sopa.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (139, 'Gnocchi', 'Ñoquis italianos en salsa cremosa o tomate.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (140, 'Soba', 'Fideos de trigo sarraceno servidos fríos o en caldo.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (141, 'Beef Wellington', 'Carne de res envuelta en hojaldre con champiñones.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (142, 'Chana Masala', 'Plato indio de garbanzos con especias.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (143, 'Sopa de Calamares', 'Sopa suave con calamares frescos y caldo especiado.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (144, 'Crepes Suzette', 'Crepes flambé con una salsa de naranja.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (145, 'Jambalaya', 'Plato cajún con arroz, carne y mariscos.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (146, 'Mole Poblano', 'Mole tradicional con chocolate, chile y pollo.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (147, 'Currywurst', 'Sausage alemana servida con salsa de curry.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (148, 'Couscous', 'Sémola de trigo acompañada con verduras y especias.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (149, 'Chicken Parmesan', 'Pechuga de pollo empanada con salsa marinara y queso.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (150, 'Burritos', 'Tortilla de harina rellena de carne, frijoles y queso.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (151, 'Paella de Mariscos', 'Arroz con mariscos frescos y verduras, cocinado al estilo tradicional.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (152, 'Croquetas', 'Croquetas crujientes rellenas de jamón, pollo o queso.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (153, 'Ceviche de Camarón', 'Camarones frescos marinados en jugo de limón con cebolla y cilantro.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (154, 'Papas Fritas', 'Papas crujientes y doradas, acompañadas de salsa o condimentos.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (155, 'Lasagna Bolognesa', 'Lasagna con carne molida en salsa boloñesa, cubierto con queso.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (156, 'Tacos de Carnitas', 'Tacos rellenos de carne de cerdo desmenuzada y especiada.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (157, 'Hot Dogs', 'Salchichas servidas en pan con una variedad de toppings.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (158, 'Shawarma', 'Carne asada, envuelta en pan árabe y acompañada de salsa tahini.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (159, 'Pasta Primavera', 'Pasta con verduras frescas salteadas en aceite de oliva y ajo.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (160, 'Pizza de Pepperoni', 'Pizza clásica con tomate, queso y rodajas de pepperoni.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (161, 'Pollo al Horno', 'Pollo asado con hierbas y especias, acompañado de papas y vegetales.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (162, 'Burritos de Pollo', 'Burritos rellenos de pollo desmenuzado, arroz, frijoles y guacamole.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (163, 'Sushi de Atún', 'Rollos de sushi con atún fresco, aguacate y arroz.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (164, 'Hamburguesa Vegana', 'Hamburguesa a base de plantas, ideal para vegetarianos y veganos.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (165, 'Empanadas de Pollo', 'Empanadas rellenas de pollo sazonado y fritas hasta dorarse.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (166, 'Pollo al Mole', 'Pollo cubierto con una salsa de mole tradicional mexicana.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (167, 'Cordero a la Parrilla', 'Cordero asado a la parrilla con hierbas y especias.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (168, 'Tacos de Pescado', 'Tacos con filete de pescado frito o a la parrilla, acompañados de ensalada.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (169, 'Pasta al Carbonara', 'Pasta con salsa cremosa de huevo, panceta y queso parmesano.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (170, 'Crepes de Nutella', 'Crepes rellenas de crema de avellanas Nutella y frutas frescas.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (171, 'Pasta al Pesto Genovese', 'Pasta servida con salsa de albahaca, ajo, piñones y aceite de oliva.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (172, 'Chiles Rellenos', 'Chiles poblanos rellenos de carne o queso, bañados en salsa.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (173, 'Quesadillas', 'Tortillas rellenas de queso derretido y otros ingredientes, como pollo o flor de calabaza.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (174, 'Pancakes', 'Pancakes esponjosos, servidos con sirope de arce y frutas.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (175, 'Curry de Pollo', 'Pollo cocinado en salsa de curry especiada con leche de coco.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (176, 'Ramen', 'Sopa japonesa de fideos con caldo de pollo, cerdo o miso.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (177, 'Alitas de Pollo', 'Alitas de pollo fritas o a la parrilla, con salsa a elección.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (178, 'Babka de Chocolate', 'Pan dulce con chocolate y nueces, tradicional de Europa del Este.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (179, 'Fish and Chips', 'Pescado empanado y frito, acompañado de papas fritas.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (180, 'Tarta de Limón', 'Pastel de limón con base crujiente y relleno cremoso.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (181, 'Tacos de Barbacoa', 'Tacos con carne de cordero o res cocinada a fuego lento.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (182, 'Galletas de Avena', 'Galletas caseras con avena, pasas y nueces.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (183, 'Sopa de Fideos', 'Sopa ligera con fideos, pollo y verduras frescas.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (184, 'Camarones Empanizados', 'Camarones empanizados y fritos, servidos con salsa tártara.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (185, 'Bruschetta', 'Tostadas de pan con tomate, ajo, albahaca y aceite de oliva.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (186, 'Tostadas de Pollo', 'Tostadas con pollo desmenuzado, crema y salsa.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (187, 'Muffins', 'Muffins esponjosos con ingredientes como frutos rojos o chocolate.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (188, 'Curry de Garbanzos', 'Curry vegetariano con garbanzos y especias, servido con arroz.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (189, 'Ceviche de Pescado', 'Pescado fresco marinado en jugo de limón, cilantro y cebolla.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (190, 'Ensalada César', 'Ensalada con lechuga romana, crutones y aderezo César.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (191, 'Pizzas Vegetarianas', 'Pizzas con vegetales frescos como tomate, espinaca y champiñones.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (192, 'Croissant', 'Croissant suave y hojaldrado, ideal para el desayuno.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (193, 'Ratatouille', 'Plato provenzal con berenjenas, calabacines, pimientos y tomate.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (194, 'Pizza 4 Quesos', 'Pizza con cuatro tipos de queso, una delicia para los amantes del queso.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (195, 'Tarta de Manzana', 'Tarta de manzana casera con una capa crujiente y dulce.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (196, 'Steak Frites', 'Corte de carne a la parrilla acompañado de papas fritas.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (197, 'Sopa de Pollo', 'Sopa reconfortante de pollo con fideos y verduras.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (198, 'Patatas al Pobre', 'Patatas cocinadas con ajo, cebolla y pimientos.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (199, 'Ensalada de Quinoa', 'Ensalada fresca con quinoa, pepino, tomate y hierbas.');
INSERT INTO FIDE_CATEGORIA_TB (id_categoria, nombre, descripcion) VALUES (200, 'Churros Rellenos', 'Churros rellenos de crema o chocolate, servidos con azúcar.');


