INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (1, 'Administrador');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (2, 'Vendedor');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (3, 'Usuario');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (4, 'Administrador');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (5, 'Moderador');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (6, 'Usuario');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (7, 'Invitado');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (8, 'Superusuario');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (9, 'Analista');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (10, 'Soporte');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (11, 'Desarrollador');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (12, 'Líder');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (13, 'Gerente');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (14, 'Director');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (15, 'Coordinador');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (16, 'Operador');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (17, 'Empleado');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (18, 'Cliente');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (19, 'Proveedor');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (20, 'Socio');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (21, 'Consultor');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (22, 'Auditor');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (23, 'Administrador de sistema');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (24, 'Técnico');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (25, 'Asesor');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (26, 'Jefe de área');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (27, 'Vendedor');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (28, 'Marketing');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (29, 'Contable');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (30, 'Financiero');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (31, 'Especialista');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (32, 'Project Manager');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (33, 'Business Analyst');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (34, 'Director de IT');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (35, 'CEO');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (36, 'CFO');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (37, 'CTO');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (38, 'CMO');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (39, 'COO');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (40, 'RRHH');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (41, 'Diseñador');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (42, 'Programador');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (43, 'Tester');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (44, 'Data Analyst');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (45, 'Data Scientist');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (46, 'Ingeniero de software');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (47, 'Administrador de base de datos');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (48, 'DevOps');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (49, 'QA Tester');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (50, 'Consultor técnico');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (51, 'Consultor de negocios');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (52, 'Asistente administrativo');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (53, 'Recepcionista');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (54, 'Asistente de ventas');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (55, 'Secretaria');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (56, 'Asistente de recursos humanos');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (57, 'Responsable de calidad');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (58, 'Consultor en IT');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (59, 'Coordinador de proyecto');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (60, 'Analista de procesos');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (61, 'Director de operaciones');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (62, 'Ingeniero de redes');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (63, 'Desarrollador web');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (64, 'Programador backend');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (65, 'Programador frontend');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (66, 'Diseñador gráfico');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (67, 'Comunicaciones');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (68, 'Líder de equipo');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (69, 'Analista funcional');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (70, 'Consultor SAP');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (71, 'Especialista en marketing');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (72, 'Desarrollador de aplicaciones móviles');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (73, 'Diseñador de experiencia de usuario');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (74, 'Analista de datos');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (75, 'Investigador de mercado');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (76, 'Director de ventas');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (77, 'Jefe de marketing');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (78, 'Director de recursos humanos');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (79, 'Líder de desarrollo de producto');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (80, 'Gerente de proyectos');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (81, 'Gerente de ventas');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (82, 'Gerente de marketing');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (83, 'Técnico de soporte');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (84, 'Administrador de red');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (85, 'Especialista en SEO');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (86, 'Desarrollador de backend');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (87, 'Desarrollador de frontend');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (88, 'Consultor en administración');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (89, 'Líder de equipo de ventas');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (90, 'Responsable de formación');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (91, 'Consultor de transformación digital');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (92, 'Coordinador de marketing');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (93, 'Director de comunicación');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (94, 'Consultor en finanzas');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (95, 'Director de estrategia');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (96, 'Desarrollador de software');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (97, 'Ingeniero en telecomunicaciones');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (98, 'Analista de calidad');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (99, 'Administrador de sistemas');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (100, 'Consultor de procesos');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (101, 'Asesor de IT');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (102, 'Diseñador de interfaces');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (103, 'Especialista en cloud');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (104, 'Analista de riesgos');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (105, 'Gerente de operaciones');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (106, 'Consultor en marketing');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (107, 'Técnico en sistemas');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (108, 'Administrador de servicios');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (109, 'Responsable de comunicación');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (110, 'Coordinador de ventas');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (111, 'Director de innovación');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (112, 'Analista de sistemas');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (113, 'Consultor de comunicación');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (114, 'Especialista en ciberseguridad');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (115, 'Desarrollador de videojuegos');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (116, 'Consultor en telecomunicaciones');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (117, 'Administrador de proyectos');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (118, 'Consultor en recursos humanos');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (119, 'Director de IT');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (120, 'Especialista en programación');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (121, 'Desarrollador de aplicaciones');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (122, 'Gerente de tecnología');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (123, 'Consultor en tecnología');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (124, 'Coordinador de IT');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (125, 'Especialista en bases de datos');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (126, 'Consultor en diseño');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (127, 'Director de seguridad');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (128, 'Analista de negocio');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (129, 'Ingeniero de sistemas');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (130, 'Consultor de calidad');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (131, 'Responsable de producto');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (132, 'Consultor en software');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (133, 'Gerente de desarrollo');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (134, 'Administrador de infraestructura');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (135, 'Consultor en seguridad');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (136, 'Desarrollador de soluciones');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (137, 'Analista de IT');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (138, 'Director de productos');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (139, 'Consultor en innovación');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (140, 'Especialista en bases de datos');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (141, 'Consultor en gestión');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (142, 'Asesor técnico');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (143, 'Especialista en redes');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (144, 'Director de investigación');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (145, 'Gerente de sistemas');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (146, 'Responsable de software');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (147, 'Consultor en gestión de proyectos');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (148, 'Director de calidad');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (149, 'Especialista en marketing digital');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (150, 'Consultor en análisis');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (151, 'Desarrollador de productos');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (152, 'Consultor de análisis');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (153, 'Director de desarrollo');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (154, 'Consultor en programación');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (155, 'Responsable de tecnología');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (156, 'Consultor en programación avanzada');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (157, 'Analista de calidad de software');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (158, 'Consultor en integración');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (159, 'Director de tecnología');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (160, 'Desarrollador front-end');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (161, 'Consultor de automatización');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (162, 'Especialista en big data');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (163, 'Consultor en informática');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (164, 'Director de informática');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (165, 'Consultor en análisis de datos');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (166, 'Desarrollador backend avanzado');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (167, 'Consultor en análisis de negocios');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (168, 'Consultor en redes sociales');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (169, 'Especialista en datos');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (170, 'Analista de seguridad');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (171, 'Consultor en administración de sistemas');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (172, 'Desarrollador de backend senior');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (173, 'Director de ventas y marketing');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (174, 'Consultor en desarrollo de software');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (175, 'Director de formación');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (176, 'Consultor en programación de sistemas');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (177, 'Especialista en desarrollo de software');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (178, 'Consultor en ventas');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (179, 'Desarrollador de front-end avanzado');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (180, 'Analista de marketing');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (181, 'Especialista en blockchain');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (182, 'Consultor en marketing digital');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (183, 'Director de análisis');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (184, 'Desarrollador de juegos');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (185, 'Consultor en servicios web');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (186, 'Desarrollador de soluciones web');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (187, 'Director de calidad y seguridad');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (188, 'Especialista en tecnología');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (189, 'Consultor en plataformas digitales');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (190, 'Administrador de seguridad');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (191, 'Consultor en metodologías ágiles');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (192, 'Desarrollador en inteligencia artificial');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (193, 'Consultor en soluciones tecnológicas');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (194, 'Director de innovación y desarrollo');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (195, 'Especialista en datos estructurados');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (196, 'Consultor en integración de sistemas');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (197, 'Desarrollador de infraestructura');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (198, 'Consultor en desarrollo de soluciones');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (199, 'Especialista en inteligencia artificial');
INSERT INTO FIDE_ROL_TB (id_rol, nombre) VALUES (200, 'Consultor en automatización de procesos');


