INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (1, 120, 'Calle Ficticia 123, Ciudad Real, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (2, 121, 'Avenida Libertad 45, Madrid, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (3, 122, 'Calle Mayor 67, Barcelona, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (4, 123, 'Calle del Sol 89, Valencia, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (5, 124, 'Plaza de la Constitución 34, Sevilla, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (6, 125, 'Carrer del Nord 12, Girona, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (7, 126, 'Calle Los Pinos 78, Málaga, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (8, 127, 'Avenida de Andalucía 56, Córdoba, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (9, 128, 'Calle del Mar 14, Alicante, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (10, 129, 'Calle Princesa 101, Zaragoza, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (11, 130, 'Avenida de los Álamos 23, Toledo, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (12, 131, 'Calle de las Flores 21, Bilbao, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (13, 132, 'Calle La Paz 34, Valladolid, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (14, 133, 'Calle Benito Pérez Galdós 65, Salamanca, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (15, 134, 'Avenida de la República 80, Granada, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (16, 135, 'Calle de los Cipreses 49, Oviedo, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (17, 136, 'Plaza de la Catedral 9, Murcia, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (18, 137, 'Calle de la Rambla 56, Barcelona, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (19, 138, 'Calle Los Lirios 88, Palma de Mallorca, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (20, 139, 'Avenida de los Tilos 54, Santander, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (21, 140, 'Calle La Luna 12, Vigo, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (22, 141, 'Calle Gran Vía 100, Madrid, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (23, 142, 'Calle del Pilar 65, Oviedo, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (24, 143, 'Avenida Europa 25, Gijón, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (25, 144, 'Calle Esmeralda 47, Alicante, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (26, 145, 'Calle del Río 21, León, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (27, 146, 'Avenida Reyes Católicos 82, Cáceres, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (28, 147, 'Calle Santiago 35, Valladolid, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (29, 148, 'Carrer de la Pau 10, Girona, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (30, 149, 'Calle La Gloria 23, Salamanca, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (31, 150, 'Avenida del Sol 19, Málaga, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (32, 151, 'Calle Las Fuentes 40, Pamplona, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (33, 152, 'Calle de los Jardines 72, Burgos, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (34, 153, 'Avenida La Paz 99, Bilbao, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (35, 154, 'Calle de la Luna 19, León, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (36, 155, 'Avenida del Norte 77, Sevilla, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (37, 156, 'Calle Real 23, Valencia, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (38, 157, 'Calle del Olivo 50, Madrid, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (39, 158, 'Calle del Pilar 21, Santiago, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (40, 159, 'Avenida del Mar 10, Málaga, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (41, 160, 'Calle Río Tajo 63, Albacete, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (42, 161, 'Plaza Mayor 80, Salamanca, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (43, 162, 'Calle del Sol 12, Cáceres, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (44, 163, 'Avenida Zaragoza 5, Huesca, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (45, 164, 'Calle Cuesta 67, Santander, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (46, 165, 'Avenida Los Tilos 18, Granada, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (47, 166, 'Calle de la Fuente 11, A Coruña, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (48, 167, 'Carrer de la Mar 32, Barcelona, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (49, 168, 'Avenida de Europa 45, Madrid, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (50, 169, 'Calle del Carmen 80, Valladolid, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (51, 170, 'Calle Nueva 101, Barcelona, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (52, 171, 'Calle del Prado 88, Bilbao, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (53, 172, 'Avenida del Mar 54, Valencia, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (54, 173, 'Calle del Sol 102, Madrid, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (55, 174, 'Calle San Juan 45, Málaga, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (56, 175, 'Calle los Abetos 58, Sevilla, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (57, 176, 'Avenida de la Reina 63, Madrid, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (58, 177, 'Calle Martín 39, Zaragoza, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (59, 178, 'Calle de las Palmas 70, Valencia, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (60, 179, 'Calle de las Azucenas 51, Salamanca, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (61, 180, 'Calle del Rey 112, Madrid, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (62, 181, 'Avenida Cataluña 21, Barcelona, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (63, 182, 'Calle Gran Vía 98, Madrid, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (64, 183, 'Calle San Francisco 32, Valladolid, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (65, 184, 'Calle del Olmo 84, Granada, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (66, 185, 'Carrer de Pau 11, Girona, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (67, 186, 'Calle de la Luna 28, Madrid, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (68, 187, 'Avenida de la Constitución 123, Sevilla, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (69, 188, 'Calle El Pilar 57, Zaragoza, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (70, 189, 'Calle Borrón 65, Alicante, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (71, 190, 'Avenida de Santa Teresa 34, Madrid, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (72, 191, 'Calle de los Angeles 44, Barcelona, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (73, 192, 'Calle del Pino 13, Toledo, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (74, 193, 'Avenida de la Sierra 58, Huesca, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (75, 194, 'Calle Constitución 32, Oviedo, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (76, 195, 'Calle Pilarica 61, Valencia, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (77, 196, 'Avenida Las Américas 98, A Coruña, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (78, 197, 'Calle Principal 49, Salamanca, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (79, 198, 'Calle del Oro 67, Santander, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (80, 199, 'Avenida del Valle 19, Bilbao, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (81, 200, 'Calle Mayor 45, Málaga, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (82, 201, 'Avenida Juan Carlos 78, Alicante, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (83, 202, 'Calle del Rayo 56, Toledo, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (84, 203, 'Calle del Teide 88, Valencia, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (85, 204, 'Avenida de la Aurora 72, Madrid, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (86, 205, 'Calle La Marea 13, Bilbao, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (87, 206, 'Calle del Cielo 21, Granada, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (88, 207, 'Avenida Andalucía 78, Sevilla, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (89, 208, 'Calle Martín de los Heros 94, Madrid, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (90, 209, 'Calle Vallehermoso 23, Salamanca, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (91, 210, 'Calle La Luna 102, Toledo, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (92, 211, 'Avenida del Sol 56, Valencia, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (93, 212, 'Calle Virgen del Carmen 18, Bilbao, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (94, 213, 'Calle Alcalá 79, Madrid, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (95, 214, 'Avenida del Mar 34, Gijón, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (96, 215, 'Calle Delicias 56, Zaragoza, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (97, 216, 'Avenida de los Álamos 10, Cáceres, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (98, 217, 'Calle del Lago 23, León, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (99, 218, 'Calle Fuensanta 87, A Coruña, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (100, 219, 'Avenida La Rioja 56, La Rioja, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (101, 220, 'Calle del Sol 40, Córdoba, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (102, 221, 'Calle de la Luna 112, Granada, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (103, 222, 'Avenida de la Paz 65, Salamanca, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (104, 223, 'Calle Virgen del Pilar 53, Zaragoza, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (105, 224, 'Avenida del Norte 82, Huesca, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (106, 225, 'Calle del Mar 77, Alicante, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (107, 226, 'Calle Gran Sol 44, Valencia, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (108, 227, 'Avenida de Aragón 61, Madrid, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (109, 228, 'Calle de los Álamos 94, Sevilla, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (110, 229, 'Calle del Mar 23, Cádiz, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (111, 230, 'Avenida del Castillo 12, Toledo, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (112, 231, 'Calle Cruz Blanca 76, León, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (113, 232, 'Calle Miguel Hernández 92, Madrid, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (114, 233, 'Avenida Marítima 45, Tenerife, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (115, 234, 'Calle Nueva 56, Oviedo, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (116, 235, 'Avenida Cataluña 43, Barcelona, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (117, 236, 'Calle Santa María 89, Burgos, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (118, 237, 'Avenida del Rio 33, León, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (119, 238, 'Calle de los Pinos 101, Valencia, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (120, 239, 'Avenida Gran Vía 23, Madrid, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (121, 240, 'Calle Santa Teresa 17, Alicante, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (122, 241, 'Calle del Bosque 81, Toledo, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (123, 242, 'Avenida de la Independencia 54, Salamanca, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (124, 243, 'Calle de los Pajaritos 12, Bilbao, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (125, 244, 'Calle Juan de la Cierva 43, Sevilla, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (126, 245, 'Avenida Libertad 55, Zaragoza, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (127, 246, 'Calle de la Paz 100, Madrid, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (128, 247, 'Avenida de Valencia 89, Alicante, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (129, 248, 'Calle San Sebastián 13, Oviedo, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (130, 249, 'Calle Puerta del Sol 62, Madrid, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (131, 250, 'Calle del Triunfo 77, Salamanca, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (132, 251, 'Avenida de la Playa 19, Valencia, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (133, 252, 'Calle Cervantes 43, Sevilla, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (134, 253, 'Calle General Yagüe 33, Madrid, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (135, 254, 'Avenida del Puerto 56, Barcelona, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (136, 255, 'Calle de los Ríos 19, Málaga, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (137, 256, 'Calle Héroes 51, Madrid, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (138, 257, 'Calle San Antonio 28, Valencia, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (139, 258, 'Avenida Parque 98, Zaragoza, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (140, 259, 'Calle del Río 24, Barcelona, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (141, 260, 'Avenida de la Catedral 16, Bilbao, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (142, 261, 'Calle Francisco de Goya 72, Madrid, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (143, 262, 'Calle de la Salud 19, Alicante, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (144, 263, 'Avenida Los Castros 45, Santander, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (145, 264, 'Calle de la Sierra 73, Huesca, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (146, 265, 'Calle del Centro 31, Zaragoza, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (147, 266, 'Avenida Marqués 98, Madrid, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (148, 267, 'Calle La Paz 23, Cáceres, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (149, 268, 'Avenida Gran Canaria 12, Las Palmas, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (150, 269, 'Calle del Rey 55, Málaga, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (151, 270, 'Calle de la Princesa 22, Madrid, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (152, 271, 'Avenida de la Reina 48, Alicante, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (153, 272, 'Calle Cerdán 34, Zaragoza, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (154, 273, 'Calle del Valle 82, Sevilla, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (155, 274, 'Avenida del Ejercito 65, Salamanca, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (156, 275, 'Calle de la Libertad 33, Burgos, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (157, 276, 'Calle Palma 18, León, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (158, 277, 'Avenida de Valencia 45, Madrid, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (159, 278, 'Calle España 91, Santander, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (160, 279, 'Calle General Álvarez 28, Barcelona, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (161, 280, 'Avenida Mediterráneo 10, Alicante, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (162, 281, 'Calle Río 54, Zaragoza, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (163, 282, 'Calle del Sol 88, Valencia, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (164, 283, 'Avenida Sierra 23, León, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (165, 284, 'Calle del Águila 16, Granada, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (166, 285, 'Calle de la Cruz 11, Burgos, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (167, 286, 'Avenida del Mar 34, Tarragona, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (168, 287, 'Calle Río Turia 19, Valencia, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (169, 288, 'Avenida Colón 47, Madrid, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (170, 289, 'Calle de los Jardines 65, Málaga, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (171, 290, 'Calle de la Estación 28, Granada, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (172, 291, 'Calle San José 44, Albacete, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (173, 292, 'Avenida Puente 17, Salamanca, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (174, 293, 'Calle Mayor 60, Toledo, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (175, 294, 'Avenida Los Olivos 23, Sevilla, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (176, 295, 'Calle Sierra de Madrid 56, Huesca, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (177, 296, 'Calle Río de la Plata 89, Valencia, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (178, 297, 'Avenida de la República 33, Santander, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (179, 298, 'Calle Las Palmas 41, Madrid, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (180, 299, 'Avenida de Cádiz 22, Sevilla, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (181, 300, 'Calle de la Luz 77, Cádiz, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (182, 301, 'Calle de la Mar 31, Toledo, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (183, 302, 'Avenida de las Aguas 19, Zaragoza, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (184, 303, 'Calle de la Estrella 88, Barcelona, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (185, 304, 'Avenida de Soria 12, Madrid, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (186, 305, 'Calle Sevilla 45, Salamanca, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (187, 306, 'Avenida del Sol 31, Valencia, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (188, 307, 'Calle de los Remedios 56, Zaragoza, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (189, 308, 'Calle Los Robles 23, Barcelona, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (190, 309, 'Avenida Montaña 13, Madrid, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (191, 310, 'Calle del Carmen 61, Alicante, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (192, 311, 'Calle Bilbao 44, León, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (193, 312, 'Avenida del Norte 18, Burgos, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (194, 313, 'Calle del Castillo 52, Sevilla, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (195, 314, 'Calle Delicias 88, Málaga, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (196, 315, 'Avenida de la Paz 21, Madrid, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (197, 316, 'Calle Santa Teresa 10, Barcelona, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (198, 317, 'Avenida Puente del Río 13, Zaragoza, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (199, 318, 'Calle de la Catedral 25, Valencia, España');
INSERT INTO FIDE_DIRECCION_TB (id_direccion, id_cliente, direccion) VALUES (200, 319, 'Calle del Viento 60, Madrid, España');
