---CREAR USUARIO--
CREATE USER grupo6 IDENTIFIED BY 123;
/
---PERMISOS
GRANT CONNECT, RESOURCE, CREATE SESSION TO grupo6;
GRANT CREATE VIEW TO grupo6;
GRANT DBA TO grupo6;

/
ALTER SESSION SET CONTAINER = XEPDB1;
---CREAR TABLESPACE---
CREATE TABLESPACE proyecto6
DATAFILE 'C:\app\gsalex\product\21c\oradata\XE\proyecto.dbf' SIZE 100M
AUTOEXTEND ON;
/
---ASIGNAR TABLESPACE---
ALTER USER grupo6 DEFAULT TABLESPACE proyecto6;
/
---CREAR PROFILE---
CREATE PROFILE proyecto6 LIMIT  
    SESSIONS_PER_USER 2
    CPU_PER_SESSION UNLIMITED
    CPU_PER_CALL UNLIMITED
    CONNECT_TIME 60
    IDLE_TIME 10
    FAILED_LOGIN_ATTEMPTS 3
    PASSWORD_LIFE_TIME 90;
/
---ASIGNAR PROFILE---
ALTER USER grupo6  PROFILE proyecto6;
/
SELECT username, default_tablespace 
FROM dba_users 
WHERE username = 'GRUPO6';
/
SELECT username, profile 
FROM dba_users 
WHERE username = 'GRUPO6';

GRANT CREATE VIEW TO grupo6;

SELECT USERNAME FROM DBA_USERS WHERE USERNAME = 'GRUPO6';
GRANT CREATE VIEW TO grupo6;

alter user grupo6 account unlock;
